[versions]
asm_version = "9.7"
jb_annotations_version = "24.1.0"
apache_commons_compress_version = "1.26.2"
kotlin_coroutines_version = "1.9.0-RC"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm_version" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm_version" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm_version" }
asm_analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm_version" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm_version" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jb_annotations_version" }
jetbrains_annotations_j5 = { module = "org.jetbrains:annotations-java5", version.ref = "jb_annotations_version" }
jetbrains_annotations_kmp = { module = "com.sschr15.annotations:jb-annotations-kmp", version.ref = "jb_annotations_version" }

appache_commons_compress = { module = "org.apache.commons:commons-compress", version.ref = "apache_commons_compress_version" }

kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines_version" }
