name: Build Snapshot

on:
  push:
    branches-ignore:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 7
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '7'

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish
        run: ./gradlew publish -Pversion_snapshot -Pmvn.user=${{ secrets.MAVEN_USER }} -Pmvn.key=${{ secrets.MAVEN_TOKEN }} -x test --info

      - uses: actions/upload-artifact@v4
        with:
          name: Snapshot Artifacts
          path: ./build/libs/
